/*
 *    Copyright (c) 2012-2013 Qualcomm Technologies, Inc. All Rights Reserved.
 *    Qualcomm Technologies Proprietary and Confidential.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qualcomm_listen_ListenReceiver */

#ifndef _Included_com_qualcomm_listen_ListenReceiver
#define _Included_com_qualcomm_listen_ListenReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qualcomm_listen_ListenReceiver
 * Method:    init
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenReceiver_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_qualcomm_listen_ListenReceiver
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenReceiver_release
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
