/*
 *    Copyright (c) 2012-2013 Qualcomm Technologies, Inc. All Rights Reserved.
 *    Qualcomm Technologies Proprietary and Confidential.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qualcomm_listen_ListenSoundModel */

#ifndef _Included_com_qualcomm_listen_ListenSoundModel
#define _Included_com_qualcomm_listen_ListenSoundModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    verifyUserRecording
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ShortBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_verifyUserRecording
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    getSizeWhenExtended
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_getSizeWhenExtended
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    extend
 * Signature: (Ljava/nio/ByteBuffer;I[Ljava/nio/ShortBuffer;Ljava/nio/ByteBuffer;Lcom/qualcomm/listen/ListenTypes/ConfidenceData;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_extend
  (JNIEnv *, jclass, jobject, jint, jobjectArray, jobject, jobject);

/*
 * Class:     com_qualcomm_listen_ListenSoundModel
 * Method:    parseVWUDetectionEventData
 * Signature: (Ljava/nio/ByteBuffer;Lcom/qualcomm/listen/ListenTypes/EventData;Lcom/qualcomm/listen/ListenTypes/VoiceWakeupDetectionData;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenSoundModel_parseVWUDetectionEventData
  (JNIEnv *, jclass, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
