/*
 *    Copyright (c) 2012-2013 Qualcomm Technologies, Inc. All Rights Reserved.
 *    Qualcomm Technologies Proprietary and Confidential.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qualcomm_listen_ListenVoiceWakeupSession */

#ifndef _Included_com_qualcomm_listen_ListenVoiceWakeupSession
#define _Included_com_qualcomm_listen_ListenVoiceWakeupSession
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qualcomm_listen_ListenVoiceWakeupSession
 * Method:    getParam
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qualcomm_listen_ListenVoiceWakeupSession_getParam
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_qualcomm_listen_ListenVoiceWakeupSession
 * Method:    registerSoundModel
 * Signature: (Lcom/qualcomm/listen/ListenTypes/SoundModelParams;)I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenVoiceWakeupSession_registerSoundModel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_qualcomm_listen_ListenVoiceWakeupSession
 * Method:    deregisterSoundModel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qualcomm_listen_ListenVoiceWakeupSession_deregisterSoundModel
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
