LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := cmcc_default.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := cmcc_field.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := cmcc_lab_csfb.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := cmcc_lab.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := cta_cdma.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := cta_default.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := cta_tds_cdma.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := ct.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gcf_2g_protocol_343.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gcf_2g_sim.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gcf_3g_sim.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := gcf_default.mbn
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS := optional debug
LOCAL_MODULE_CLASS := EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)/modem_config
include $(BUILD_PREBUILT)
