/*=============================================================================
        Copyright 2005-2006 Qualcomm Technologies, Inc.
               All Rights Reserved.
            Qualcomm Technologies Proprietary/GTDR
============================================================================ 
*/
// Copyright (c) 2006, 2007 Qualcomm Technologies, Inc.

/* Auto generated code by the Component Services IDL compiler.
 * Warning: DO NOT EDIT THIS FILE. CHANGES MAY BE LOST.
 */

#ifndef AEECREALLOC_H
#define AEECREALLOC_H

#if !defined(AEEINTERFACE_CPLUSPLUS)

#include "AEEStdDef.h"
#define AEECLSID_CRealloc 0x1030522

#else /* C++ */

#include "AEEStdDef.h"
const AEECLSID AEECLSID_CRealloc = 0x1030522;

#endif /* !defined(AEEINTERFACE_CPLUSPLUS) */

/*==========================================================================
   CLASS DOCUMENTATION
============================================================================

AEECLSID_CRealloc

Description:
   
   AEECLSID_CRealloc identifies the environment's default heap.  Passing this
   class ID to IEnv_CreateInstance(piEnv,...) will obtain the heap that was
   created for piEnv.  This is the heap that is used by IEnv's own
   allocation functions.  This heap is constructed before any components in
   the environment are instantiated, and is destroyed after all IEnv_AtExit()
   calls are processed.

Default Interface:
   IRealloc

Other Supported Interfaces:
   None

See Also:
   IEnv
   IEnv_CreateInstance()
   IRealloc

============================================================================ 
*/
#endif /* #ifndef AEECREALLOC_H */
