/*==============================================================================
        Copyright 2005 Qualcomm Technologies, Inc.
               All Rights Reserved.
            Qualcomm Technologies Proprietary/GTDR
==============================================================================
*/
// Copyright (c) 2006, 2007 Qualcomm Technologies, Inc.

/* Auto generated code by the Component Services IDL compiler.
 * Warning: DO NOT EDIT THIS FILE. CHANGES MAY BE LOST.
 */

#ifndef AEECPRIVSET_H
#define AEECPRIVSET_H

#if !defined(AEEINTERFACE_CPLUSPLUS)

#include "AEEStdDef.h"
#define AEECLSID_CPrivSet 0x103192c

#else /* C++ */

#include "AEEStdDef.h"
const AEECLSID AEECLSID_CPrivSet = 0x103192c;

#endif /* !defined(AEEINTERFACE_CPLUSPLUS) */

/*==========================================================================
   CLASS DOCUMENTATION
============================================================================

AEECLSID_CPrivSet

Description:
   AEECLSID_CPrivSet is the privilege set bound to the current environment.
   Pass this class ID to IEnv_CreateInstance() to get the current IPrivSet
   for that instance of IEnv.

Default Interface:
   IPrivSet

Other Supported Interfaces:
   None

See Also:
   IPrivSet
   IEnv
   IPrivSet
   IEnv_CreateInstance()

=============================================================================

*/
#endif /* #ifndef AEECPRIVSET_H */
