/*
=======================================================================
                  Copyright 2005 Qualcomm Technologies, Inc.
                         All Rights Reserved.
                      Qualcomm Technologies Proprietary/GTDR
=======================================================================

*/
// Copyright (c) 2006, 2007 Qualcomm Technologies, Inc.

/* Auto generated code by the Component Services IDL compiler.
 * Warning: DO NOT EDIT THIS FILE. CHANGES MAY BE LOST.
 */

#ifndef AEECSIGNALBUS_H
#define AEECSIGNALBUS_H

#if !defined(AEEINTERFACE_CPLUSPLUS)

#include "AEEStdDef.h"
#define AEECLSID_CSignalBus 0x1036d2c

#else /* C++ */

#include "AEEStdDef.h"
const AEECLSID AEECLSID_CSignalBus = 0x1036d2c;

#endif /* !defined(AEEINTERFACE_CPLUSPLUS) */

/*=============================================================================
   CLASS DOCUMENTATION
===============================================================================

AEECLSID_CSignalBus

Description:

   AEECLSID_CSignalBus specifies a new instance of a signal bus.

   AEECLSID_CSignalBus is compatible with AEECLSID_CSignalFactory and
   AEECLSID_CSignalCBFactory.  Instances of AEECLSID_CSignalBus can be used to
   manage signals created via those compatible classes.

   MT-safe:  Instances of this class can be used safely by multiple threads.

Default Interface:
   ISignalBus

Other Supported Interfaces:
   None

See Also:
   ISignalBus
===============================================================================

*/
#endif /* #ifndef AEECSIGNALBUS_H */
