/*=============================================================================

FILE: AEECEnv.h

SERVICES:     

DESCRIPTION:  

===============================================================================
        Copyright 2005 Qualcomm Technologies, Inc.
               All Rights Reserved.
            Qualcomm Technologies Proprietary/GTDR
=============================================================================
*/
// Copyright (c) 2006, 2007 Qualcomm Technologies, Inc.

/* Auto generated code by the Component Services IDL compiler.
 * Warning: DO NOT EDIT THIS FILE. CHANGES MAY BE LOST.
 */

#ifndef AEECENV_H
#define AEECENV_H

#if !defined(AEEINTERFACE_CPLUSPLUS)

#include "AEEStdDef.h"
#define AEECLSID_CEnv 0x103a936

#else /* C++ */

#include "AEEStdDef.h"
const AEECLSID AEECLSID_CEnv = 0x103a936;

#endif /* !defined(AEEINTERFACE_CPLUSPLUS) */

/*=============================================================================
   CLASS DOCUMENTATION
===============================================================================

AEECLSID_CEnv

Description:
   This class id denotes the current environment.

Default Interface:
   IEnv

=============================================================================
*/
#endif /* #ifndef AEECENV_H */
